/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-02-27 11:30:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.student.dto.Student;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.student.dto.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Student Management</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    /* Fix navbar button alignment */\r\n");
      out.write("    .navbar-nav {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Center align the Dashboard title */\r\n");
      out.write("    .dashboard-title {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Responsive table */\r\n");
      out.write("    .table-container {\r\n");
      out.write("      overflow-x: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Align logout button properly */\r\n");
      out.write("    .logout-btn {\r\n");
      out.write("      padding: 5px 15px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");

    Student user = (Student) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("Login.jsp"); // Redirect to login if session is empty
        return;
    }
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
 String msg = (String)request.getAttribute("success_u");
           if (msg != null) { 
      out.write("\r\n");
      out.write("           <h3 class=\"failure\" id=\"errorMsg\">");
      out.print( msg );
      out.write("</h3>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("     <script>\r\n");
      out.write("            // Remove error message after 5 seconds\r\n");
      out.write("            setTimeout(function () {\r\n");
      out.write("                var msgElement = document.getElementById(\"errorMsg\");\r\n");
      out.write("                if (msgElement) {\r\n");
      out.write("                    msgElement.style.display = \"none\";  \r\n");
      out.write("                }\r\n");
      out.write("            }, 5000);\r\n");
      out.write("        </script>\r\n");
      out.write("	\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  \r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <a class=\"navbar-brand navbar-primary\" href=\"#\">Welcome : ");
      out.print( user.getName() );
      out.write(" </a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(user.getId() == 1){ 
      out.write("\r\n");
      out.write("  		<li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"viewuser.jsp\">view user</a>\r\n");
      out.write("          </li>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"reset.jsp\">Reset Password</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"update.jsp\">Update Data</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <form action=\"logout\" method=\"post\">\r\n");
      out.write("              <input class=\"btn btn-danger logout-btn\" type=\"submit\" name=\"logout\" value=\"Logout\">\r\n");
      out.write("            </form>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <!-- Dashboard Title -->\r\n");
      out.write("  <div class=\"container mt-4\">\r\n");
      out.write("    <h1 class=\"dashboard-title\">Dashboard</h1>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- User Section -->\r\n");
      out.write("  <div class=\"container table-container mt-4\">\r\n");
      out.write("    <h3>View Your Data</h3>\r\n");
      out.write("    <table class=\"table table-hover table-bordered text-center\">\r\n");
      out.write("      <thead class=\"table-dark\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>Id</th>\r\n");
      out.write("          <th>Name</th>\r\n");
      out.write("          <th>Phone</th>\r\n");
      out.write("          <th>Mail ID</th>\r\n");
      out.write("          <th>Branch</th>\r\n");
      out.write("          <th>Location</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("      <tbody>\r\n");
      out.write("        <!-- Data Rows Will Be Added Here -->\r\n");
      out.write("        <tr>\r\n");
      out.write("        	<td> ");
      out.print( user.getId() );
      out.write(" </td>\r\n");
      out.write("        	<td> ");
      out.print( user.getName());
      out.write(" </td>\r\n");
      out.write("        	<td> ");
      out.print( user.getPhone() );
      out.write(" </td>\r\n");
      out.write("        	<td> ");
      out.print( user.getMail());
      out.write(" </td>\r\n");
      out.write("        	<td> ");
      out.print( user.getBranch());
      out.write(" </td>\r\n");
      out.write("        	<td> ");
      out.print( user.getLoc());
      out.write(" </td>\r\n");
      out.write("        \r\n");
      out.write("        </tr>\r\n");
      out.write("      </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
